version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - pg

  backend:
    build: ./kanbanback/kanbanback_new/kanban_board
    container_name: django_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - pg

  frontend:
    build: ./kanbanfront/kanbanfront_new/kanban_front
    container_name: react_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  
volumes:
  pg_data:
  
networks:
  pg:
