# Generated by Django 3.0.3 on 2025-02-15 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.IntegerField(primary_key=True, serialize=False)),
                ('board_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'board',
            },
        ),
        migrations.CreateModel(
            name='Col',
            fields=[
                ('col_id', models.IntegerField(primary_key=True, serialize=False)),
                ('col_name', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='kanban.Board')),
            ],
            options={
                'db_table': 'col',
            },
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('empname', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('pass_field', models.CharField(blank=True, db_column='pass', max_length=255, null=True)),
            ],
            options={
                'db_table': 'emp',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(blank=True, max_length=255, null=True)),
                ('task_type', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.CharField(blank=True, max_length=255, null=True)),
                ('acceptance_criteria', models.CharField(blank=True, max_length=255, null=True)),
                ('story_points', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
                ('assignee', models.ForeignKey(blank=True, db_column='assignee', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_tasks', to='kanban.Emp')),
                ('col', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='kanban.Col')),
                ('reporter', models.ForeignKey(blank=True, db_column='reporter', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reported_tasks', to='kanban.Emp')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('comment_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('comment_time', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='kanban.Task')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.AddField(
            model_name='board',
            name='emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='kanban.Emp'),
        ),
    ]
