# Generated by Django 5.1.6 on 2025-02-22 21:15

from django.db import migrations

def populate_emp_table(apps, schema_editor):
    Emp = apps.get_model("your_app_name", "Emp")

    employees = [
        Emp(empname="Alice Johnson", pass_field="password123"),
        Emp(empname="Bob Brown", pass_field="securePass1"),
        Emp(empname="Charlie Wilson", pass_field="mySecretPwd"),
        Emp(empname="David Lee", pass_field="pass2024"),
        Emp(empname="Eva Adams", pass_field="strongPWD"),
        Emp(empname="Franklin White", pass_field="pass9876"),
        Emp(empname="Grace Hall", pass_field="test1234"),
        Emp(empname="Henry King", pass_field="letMeIn"),
        Emp(empname="Ivy Clarke", pass_field="superPass"),
        Emp(empname="Jack Miller", pass_field="empPass4321"),
    ]

    Emp.objects.bulk_create(employees)

class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_alter_task_status_alter_task_task_name'),
    ]

    operations = [
        migrations.RunPython(populate_emp_table),
    ]
